version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3002:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: appdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "15432:5432"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

volumes:
  pgdata:
